"""Re-import holdings from a fresh Zerodha Console Excel export.

Usage:
    python -m india_monitor.scripts.import_holdings ~/Downloads/holdings-XFG529.xlsx

Overwrites holdings.yaml in the project root. Review the diff before committing.
The long_term field is preserved from the existing holdings.yaml where a symbol
already exists; new symbols are set to long_term: false (update manually).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd
import yaml


def _find_header_row(data: pd.DataFrame) -> int:
    for i, row in data.iterrows():
        vals = " ".join(str(v) for v in row.values if str(v) != "nan").upper()
        if "SYMBOL" in vals and ("QUANTITY" in vals or "ISIN" in vals):
            return i
    raise ValueError("Could not find header row with 'Symbol' and 'Quantity' columns")


def parse_xlsx(path: Path) -> list[dict]:
    # Try Equity sheet first, fall back to Combined
    for sheet in ("Equity", "Combined"):
        try:
            raw = pd.read_excel(path, sheet_name=sheet, header=None)
            break
        except Exception:
            continue
    else:
        raise SystemExit(f"Could not read Equity or Combined sheet from {path}")

    header_idx = _find_header_row(raw)
    df = raw.iloc[header_idx:].copy()
    df.columns = df.iloc[0]
    df = df.iloc[1:].reset_index(drop=True)
    df = df.dropna(subset=["Symbol"])
    df = df[df["Symbol"] != "Symbol"]

    # Normalise column names
    df.columns = [str(c).strip() for c in df.columns]
    qty_col = next((c for c in df.columns if "Quantity Available" in c), None)
    avg_col = next((c for c in df.columns if "Average Price" in c), None)
    sector_col = next((c for c in df.columns if "Sector" in c), None)
    lt_col = next((c for c in df.columns if "Long Term" in c), None)

    holdings = []
    for _, row in df.iterrows():
        sym = str(row["Symbol"]).strip().upper()
        qty = float(row[qty_col]) if qty_col else 0.0
        avg = float(row[avg_col]) if avg_col else 0.0
        sector = str(row[sector_col]).strip() if sector_col else ""
        lt_qty = float(row[lt_col]) if lt_col and str(row[lt_col]) != "nan" else 0.0
        long_term = lt_qty > 0 and lt_qty >= qty * 0.99  # all-or-mostly long-term
        holdings.append({
            "symbol": sym,
            "quantity": qty,
            "average_cost": round(avg, 2),
            "sector": sector,
            "long_term": long_term,
        })
    return holdings


def merge_with_existing(new: list[dict], existing_path: Path) -> list[dict]:
    """Preserve long_term overrides from the existing YAML for known symbols."""
    if not existing_path.exists():
        return new
    try:
        raw = yaml.safe_load(existing_path.read_text()) or {}
        existing = {h["symbol"]: h for h in raw.get("holdings", [])}
        for h in new:
            if h["symbol"] in existing:
                h["long_term"] = existing[h["symbol"]].get("long_term", h["long_term"])
    except Exception:
        pass
    return new


def main() -> int:
    parser = argparse.ArgumentParser(description="Import holdings from Zerodha Console Excel.")
    parser.add_argument("xlsx", type=Path)
    parser.add_argument("--output", type=Path, default=None,
                        help="Output path (default: holdings.yaml in project root)")
    args = parser.parse_args()

    if not args.xlsx.exists():
        print(f"File not found: {args.xlsx}", file=sys.stderr)
        return 1

    from india_monitor.holdings_loader import project_root
    out_path = args.output or (project_root() / "holdings.yaml")

    holdings = parse_xlsx(args.xlsx)
    holdings = merge_with_existing(holdings, out_path)

    doc = {"holdings": holdings}
    with out_path.open("w") as f:
        f.write("# holdings.yaml — auto-generated by import_holdings.py\n")
        f.write(f"# Source: {args.xlsx.name}\n\n")
        yaml.dump(doc, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"Wrote {len(holdings)} holdings to {out_path}")
    print("Review long_term flags for any new positions and update manually if needed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
